/**
 * Canonical event name catalog for Shinsu Duel.
 *
 * All event names follow the convention: namespace:subject:verb (kebab-case).
 * Use these constants instead of raw strings throughout the codebase.
 */

const EVT = {
  // Game lifecycle
  GAME_STARTED:     "game:started",
  GAME_OVER:        "game:over",
  GAME_DECK_EMPTY:  "game:deck:empty",
  GAME_LIGHTHOUSES_DEPLETED: "game:lighthouses:depleted",

  // Round lifecycle
  ROUND_START:  "round:started",
  ROUND_END:    "round:ended",

  // Turn lifecycle
  TURN_START: "turn:started",
  TURN_END:   "turn:ended",

  // Unit lifecycle
  UNIT_DEPLOYED:  "unit:deployed",
  UNIT_SUMMONED:  "unit:summoned",
  ACTIVATION:     "unit:activation",
  UNIT_DESTROY_INTENT: "unit:destroy:intent",
  UNIT_DESTROYED: "unit:destroyed",
  UNIT_EVOLVED:   "unit:evolved",
  UNIT_EVOLVING:  "unit:evolving",
  UNIT_KILLED:    "unit:killed",
  UNIT_RETURNED_TO_HAND: "unit:returned-to-hand",

  // Damage
  DAMAGE_INTENT:    "unit:damage:intent",
  DAMAGE_APPLIED:   "unit:damage:applied",
  BARRIER_ABSORBED: "unit:barrier:absorbed",

  // Death (before unit:killed; cancellable by Undying)
  UNIT_DEATH_INTENT:      "unit:death:intent",
  UNIT_UNDYING_TRIGGERED: "unit:undying:saved",

  // State changes
  CARD_DRAWN:     "card:drawn",
  CARD_RECLAIMED: "card:reclaimed",
  CARD_CREATED:   "card:created",
  SHINSU_CHARGED: "shinsu:charged",
  SHINSU_SPENT:   "shinsu:spent",
  SHINSU_CHANGED: "state:shinsu:changed",
  TRAIT_GRANTED:  "state:trait:granted",
  EFFECT_UNSUPPORTED: "effect:unsupported",

  // Equipment
  EQUIPMENT_ATTACHED: "equipment:attached",
  EQUIPMENT_DETACHED: "equipment:detached",
  EQUIPMENT_IGNITED:  "equipment:ignited",

  // Modifier events (generated by ModifierStack)
  MODIFIER_GRANTED: (type) => `modifier:${type}:granted`,
  MODIFIER_REVOKED: (type) => `modifier:${type}:revoked`,
  MODIFIER_DISABLED:  "modifier:disabled",
  MODIFIER_ENABLED:   "modifier:enabled",

  // Attribute-specific
  SHINHEUH_SLOT_GRANTED:    "shinheuh:slot:granted",
  HWAYEOMSA_CHARGE_GAINED:  "hwayeomsa:charge:gained",
  HWAYEOMSA_INCINERATE_CREATED: "hwayeomsa:incinerate:created",

  // Skill
  SKILL_APPLIED: "skill:applied",
  UNIT_ABILITY_GRANTED: "unit:ability:granted",

  // Ability usage
  UNIT_ABILITY_USED:      "unit:ability:used",
  UNIT_ABILITY_INTENT:    "unit:ability:intent",
  UNIT_ABILITY_RESOLVED:  "unit:ability:resolved",

  // Decision protocol
  DECISION_PENDING:  "pending-decision",
  DECISION_RESOLVED: "decision:resolved",

  // Position switching
  UNIT_POSITION_SWITCHED: "unit:position:switched",

  // Condition-specific
  CONDITION_CLEANSED:  "state:condition:cleansed",
  CONDITION_APPLIED:   "state:condition:applied",
  CONDITION_BLOCKED:   "state:condition:blocked",

  // Lighthouse
  LIGHTHOUSE_CHANGED: "state:lighthouse:changed",

  // Heal
  HEAL_APPLIED: "unit:heal:applied",

  // Compression
  SHINSU_COMPRESSED: "shinsu:compressed",

  // Card discard
  CARD_DISCARDED: "card:discarded",

  // Steal
  UNIT_STOLEN: "unit:stolen",

  // Silence (remove traits)
  UNIT_SILENCED: "unit:silenced",

  // Hand reveal (observer-only)
  HAND_PEEKED: "hand:peeked",
};

export default EVT;
