/**
 * Canonical event name catalog for Shinsu Duel.
 *
 * All event names follow the convention: namespace:subject:verb (kebab-case).
 * Use these constants instead of raw strings throughout the codebase.
 *
 * Phase 1 legacy names (PascalCase) are listed in comments for migration reference.
 */

const EVT = {
  // ── Game lifecycle ────────────────────────────────────────────────────────
  GAME_STARTED:    "game:started",      // was OnGameStart
  GAME_OVER:       "game:over",
  GAME_DECK_EMPTY: "game:deck:empty",
  GAME_LIGHTHOUSES_DEPLETED: "game:lighthouses:depleted",

  // ── Round lifecycle ───────────────────────────────────────────────────────
  ROUND_START:     "round:started",      // was OnRoundStart
  ROUND_END:       "round:ended",        // was OnRoundEnd

  // ── Turn lifecycle ────────────────────────────────────────────────────────
  TURN_START:      "turn:started",       // was OnTurnStart
  TURN_END:        "turn:ended",         // was OnTurnEnd

  // ── Unit lifecycle ────────────────────────────────────────────────────────
  UNIT_DEPLOYED:   "unit:deployed",      // was OnDeployUnit
  UNIT_SUMMONED:   "unit:summoned",      // was OnSummonUnit
  UNIT_DESTROY_INTENT: "unit:destroy:intent",
  UNIT_DESTROYED:  "unit:destroyed",     // was OnUnitRemoved
  UNIT_EVOLVED:    "unit:evolved",
  UNIT_KILLED:     "unit:killed",

  // ── Damage ────────────────────────────────────────────────────────────────
  DAMAGE_INTENT:   "unit:damage:intent", // was OnDealDamageIntent
  DAMAGE_APPLIED:  "unit:damage:applied",// was OnDealDamageApplied
  BARRIER_ABSORBED:"unit:barrier:absorbed",

  // ── State changes ─────────────────────────────────────────────────────────
  CARD_DRAWN:      "card:drawn",
  CARD_RECLAIMED:  "card:reclaimed",
  SHINSU_CHARGED:   "shinsu:charged",
  SHINSU_SPENT:     "shinsu:spent",
  SHINSU_CHANGED:   "state:shinsu:changed",
  TRAIT_GRANTED:    "state:trait:granted",

  // ── Equipment ─────────────────────────────────────────────────────────────
  EQUIPMENT_ATTACHED: "equipment:attached",
  EQUIPMENT_DETACHED: "equipment:detached",

  // ── Modifier events (generated by ModifierStack) ──────────────────────────
  MODIFIER_GRANTED: (type) => `modifier:${type}:granted`,
  MODIFIER_REVOKED: (type) => `modifier:${type}:revoked`,
  MODIFIER_DISABLED: "modifier:disabled",
  MODIFIER_ENABLED:  "modifier:enabled",

  // ── Attribute-specific ────────────────────────────────────────────────────
  SHINHEUH_SLOT_GRANTED: "shinheuh:slot:granted",
  HWAYEOMSA_CHARGE_GAINED: "hwayeomsa:charge:gained",
  HWAYEOMSA_INCINERATE_CREATED: "hwayeomsa:incinerate:created",

  // ── Skill ─────────────────────────────────────────────────────────────────
  SKILL_APPLIED:   "skill:applied",
  UNIT_ABILITY_GRANTED: "unit:ability:granted",
};

export default EVT;
